language: node_js
node_js:
  - '10'

env:
  - NODE_ENV=testing

cache:
  directories:
    - "node_modules"

install:
  - npm install -g codecov typescript 
  - npm install
  - npm uninstall TwinePlatform/eslint-config-twine
  - npm install TwinePlatform/eslint-config-twine


script:
  - npm run lint
  - npm run cover
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always
